scope: audit-cluster
namespace: /service/
name: patroni-0

restapi:
  listen: 0.0.0.0:8008
  connect_address: ${PATRONI_RESTAPI_CONNECT_ADDRESS}
  authentication:
    username: admin
    password: ${PATRONI_admin_PASSWORD}

etcd:
  hosts: ${PATRONI_ETCD_HOSTS}
  protocol: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 10
        max_replication_slots: 10
        checkpoint_timeout: 30

  initdb:
    - encoding: UTF8
    - data-checksums

  pg_hba:
    - host replication replicator 0.0.0.0/0 md5
    - host all all 0.0.0.0/0 md5

  users:
    admin:
      password: ${PATRONI_admin_PASSWORD}
      options:
        - createrole
        - createdb

postgresql:
  listen: ${PATRONI_POSTGRESQL_LISTEN}
  connect_address: ${PATRONI_POSTGRESQL_CONNECT_ADDRESS}
  data_dir: ${PATRONI_POSTGRESQL_DATA_DIR}
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: ${PATRONI_REPLICATION_USERNAME}
      password: ${PATRONI_REPLICATION_PASSWORD}
    superuser:
      username: ${PATRONI_SUPERUSER_USERNAME}
      password: ${PATRONI_SUPERUSER_PASSWORD}
  parameters:
    max_connections: 100
    shared_buffers: 128MB
    dynamic_shared_memory_type: posix
    max_wal_size: 1GB
    min_wal_size: 80MB
    log_timezone: 'UTC'
    datestyle: 'iso, mdy'
    timezone: 'UTC'
    default_text_search_config: 'pg_catalog.english'
    log_statement: 'none'
    log_duration: off
    log_lock_waits: on
    deadlock_timeout: 1s

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false